-- ============================================================================
-- Nanno Café · Fidelidad — esquema completo de base de datos
-- ============================================================================
-- Este archivo se puede pegar entero en el SQL Editor de Supabase y ejecutar.
-- Es seguro correrlo varias veces y es seguro correrlo sobre la versión vieja:
-- no borra clientes ni historial.
--
-- DESPUÉS de correrlo hay que dar de alta al personal. Ver el paso 5 del README.
-- ============================================================================

create extension if not exists pgcrypto;

-- ----------------------------------------------------------------------------
-- 1. Tablas
-- ----------------------------------------------------------------------------

create table if not exists public.clients(
  id uuid primary key default gen_random_uuid(),
  name text not null,
  phone text,
  qr_token text not null unique default encode(gen_random_bytes(18),'hex'),
  coffees integer not null default 0 check(coffees between 0 and 4),
  free_coffee_available boolean not null default false,
  created_at timestamptz not null default now()
);

-- Clientes dados de baja: se ocultan del panel pero se conserva su historial.
alter table public.clients add column if not exists active boolean not null default true;

-- Teléfono normalizado (solo dígitos) para poder buscar y detectar repetidos
-- aunque estén cargados como "11 2345-6789", "+5491123456789", etc.
alter table public.clients
  add column if not exists phone_digits text
  generated always as (nullif(regexp_replace(coalesce(phone,''),'\D','','g'),'')) stored;

create index if not exists clients_phone_digits_idx on public.clients(phone_digits);
create index if not exists clients_active_name_idx on public.clients(active, name);

create table if not exists public.loyalty_events(
  id bigint generated by default as identity primary key,
  client_id uuid not null references public.clients(id) on delete cascade,
  event_type text not null check(event_type in('coffee','gift_redeemed')),
  created_at timestamptz not null default now(),
  performed_by uuid references auth.users(id)
);

create index if not exists loyalty_events_client_idx
  on public.loyalty_events(client_id, created_at desc);

-- Personal autorizado. Estar registrado en Supabase NO alcanza para operar:
-- además hay que estar en esta tabla. Es lo que impide que un desconocido
-- se cree una cuenta y se regale cafés.
create table if not exists public.staff(
  user_id uuid primary key references auth.users(id) on delete cascade,
  email text,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
-- 2. Quién es personal
-- ----------------------------------------------------------------------------

create or replace function public.is_staff()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists(
    select 1 from public.staff
    where user_id = auth.uid() and active
  )
$$;

grant execute on function public.is_staff() to authenticated;

-- ----------------------------------------------------------------------------
-- 3. Row Level Security
-- ----------------------------------------------------------------------------

alter table public.clients        enable row level security;
alter table public.loyalty_events enable row level security;
alter table public.staff          enable row level security;

-- Políticas viejas (versión 1): permitían todo a cualquier usuario registrado.
drop policy if exists "auth read clients"   on public.clients;
drop policy if exists "auth insert clients" on public.clients;
drop policy if exists "auth read events"    on public.loyalty_events;

drop policy if exists "staff read clients"   on public.clients;
drop policy if exists "staff insert clients" on public.clients;
drop policy if exists "staff update clients" on public.clients;
drop policy if exists "staff read events"    on public.loyalty_events;
drop policy if exists "staff read self"      on public.staff;

create policy "staff read clients"   on public.clients        for select to authenticated using(public.is_staff());
create policy "staff insert clients" on public.clients        for insert to authenticated with check(public.is_staff());
create policy "staff update clients" on public.clients        for update to authenticated using(public.is_staff()) with check(public.is_staff());
create policy "staff read events"    on public.loyalty_events for select to authenticated using(public.is_staff());
create policy "staff read self"      on public.staff          for select to authenticated using(user_id = auth.uid());

-- Nadie escribe el saldo directamente: no hay policy de UPDATE sobre coffees
-- que sirva para eso. Se cambia únicamente por las funciones de abajo.

-- ----------------------------------------------------------------------------
-- 4. Tarjeta pública del cliente (sin login)
-- ----------------------------------------------------------------------------
-- Devuelve solo lo que la tarjeta necesita mostrar. NO devuelve el teléfono:
-- quien tenga el link de un cliente no tiene por qué ver su número.

drop function if exists public.get_client_for_qr(text);

create function public.get_client_for_qr(p_qr_token text)
returns table(id uuid, name text, qr_token text, coffees integer, free_coffee_available boolean)
language sql
stable
security definer
set search_path = public
as $$
  select id, name, qr_token, coffees, free_coffee_available
  from public.clients
  where qr_token = p_qr_token and active
  limit 1
$$;

grant execute on function public.get_client_for_qr(text) to anon, authenticated;

-- ----------------------------------------------------------------------------
-- 5. Operaciones del mostrador (solo personal)
-- ----------------------------------------------------------------------------

drop function if exists public.add_coffee(uuid);
drop function if exists public.add_coffee(uuid, boolean);

create function public.add_coffee(p_client_id uuid, p_allow_rapid boolean default false)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  c integer;
  g boolean;
begin
  if not public.is_staff() then
    raise exception 'No autorizado';
  end if;

  -- Protección contra el doble toque accidental en el mostrador.
  -- Si de verdad compró dos cafés seguidos, la pantalla pregunta y reintenta.
  if not p_allow_rapid and exists(
    select 1 from public.loyalty_events
    where client_id = p_client_id
      and event_type = 'coffee'
      and created_at > now() - interval '20 seconds'
  ) then
    raise exception 'RAPID_DUPLICATE';
  end if;

  select coffees, free_coffee_available into c, g
  from public.clients where id = p_client_id and active
  for update;

  if c is null then
    raise exception 'Cliente inexistente';
  end if;

  if g then
    raise exception 'Primero hay que utilizar el regalo';
  end if;

  if c >= 3 then
    update public.clients
      set coffees = 4, free_coffee_available = true
      where id = p_client_id;
  else
    update public.clients
      set coffees = c + 1
      where id = p_client_id;
  end if;

  insert into public.loyalty_events(client_id, event_type, performed_by)
  values (p_client_id, 'coffee', auth.uid());
end
$$;

create or replace function public.redeem_gift(p_client_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if not public.is_staff() then
    raise exception 'No autorizado';
  end if;

  update public.clients
    set coffees = 0, free_coffee_available = false
    where id = p_client_id and active and free_coffee_available = true;

  if not found then
    raise exception 'No hay regalo disponible';
  end if;

  insert into public.loyalty_events(client_id, event_type, performed_by)
  values (p_client_id, 'gift_redeemed', auth.uid());
end
$$;

grant execute on function public.add_coffee(uuid, boolean) to authenticated;
grant execute on function public.redeem_gift(uuid)         to authenticated;

-- Se revoca a PUBLIC, no a anon. PostgreSQL le da EXECUTE a PUBLIC apenas se
-- crea una función, y anon accede por ahí: "revoke ... from anon" no le saca
-- nada, porque anon nunca tuvo un permiso propio que revocar. Sacándoselo a
-- PUBLIC quedan habilitados solo los roles nombrados arriba.
revoke execute on function public.add_coffee(uuid, boolean) from public;
revoke execute on function public.redeem_gift(uuid)         from public;
revoke execute on function public.is_staff()                from public;
revoke execute on function public.get_client_for_qr(text)   from public;

-- ----------------------------------------------------------------------------
-- 6. Resumen para el panel
-- ----------------------------------------------------------------------------
-- Cuenta en la base en vez de traerse todas las filas al celular.

create or replace function public.dashboard_stats()
returns table(clients_count bigint, coffees_count bigint, gifts_count bigint)
language sql
stable
security definer
set search_path = public
as $$
  select
    (select count(*) from public.clients where active),
    (select count(*) from public.loyalty_events where event_type = 'coffee'),
    (select count(*) from public.loyalty_events where event_type = 'gift_redeemed')
  where public.is_staff()
$$;

grant execute on function public.dashboard_stats() to authenticated;
revoke execute on function public.dashboard_stats() from public;
